-- KitapLab pano anketleri: tekli/coklu oy, herkese acik oranlar,
-- yalnizca pano sahibi ve adminlere acik oy veren listesi.

alter table public.panolar
  add column if not exists poll_question text,
  add column if not exists poll_allows_multiple boolean;

alter table public.panolar
  drop constraint if exists panolar_poll_fields_check;

alter table public.panolar
  add constraint panolar_poll_fields_check check (
    (poll_question is null and poll_allows_multiple is null)
    or (
      char_length(btrim(poll_question)) between 3 and 200
      and poll_allows_multiple is not null
    )
  );

create table if not exists public.pano_poll_options (
  id bigint generated by default as identity primary key,
  pano_id uuid not null references public.panolar(id) on delete cascade,
  label text not null,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (pano_id, display_order)
);

alter table public.pano_poll_options
  add column if not exists display_order integer;

-- Older installations used the required "position" column. Keep it in sync
-- while migrating those databases to display_order.
alter table public.pano_poll_options
  add column if not exists "position" integer;

alter table public.pano_poll_options
  add column if not exists sort_order integer;

with ranked_options as (
  select
    option_row.id,
    row_number() over (
      partition by option_row.pano_id
      order by option_row.id
    ) - 1 as generated_order
  from public.pano_poll_options option_row
)
update public.pano_poll_options option_row
set
  display_order = coalesce(option_row.display_order, ranked.generated_order),
  "position" = coalesce(option_row."position", ranked.generated_order),
  sort_order = coalesce(option_row.sort_order, ranked.generated_order)
from ranked_options ranked
where option_row.id = ranked.id
  and (
    option_row.display_order is null
    or option_row."position" is null
    or option_row.sort_order is null
  );

alter table public.pano_poll_options
  alter column display_order set not null;

alter table public.pano_poll_options
  alter column "position" set not null;

alter table public.pano_poll_options
  alter column sort_order set not null;

create unique index if not exists pano_poll_options_pano_order_uidx
  on public.pano_poll_options (pano_id, display_order);

create table if not exists public.pano_poll_votes (
  id bigint generated by default as identity primary key,
  pano_id uuid not null references public.panolar(id) on delete cascade,
  option_id bigint not null references public.pano_poll_options(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (option_id, user_id)
);

create unique index if not exists pano_poll_votes_option_user_uidx
  on public.pano_poll_votes (option_id, user_id);

create index if not exists pano_poll_votes_pano_user_idx
  on public.pano_poll_votes (pano_id, user_id);

alter table public.pano_poll_options enable row level security;
alter table public.pano_poll_votes enable row level security;

revoke all on table public.pano_poll_options from public, anon, authenticated;
revoke all on table public.pano_poll_votes from public, anon, authenticated;
revoke all on sequence public.pano_poll_options_id_seq from public, anon, authenticated;
revoke all on sequence public.pano_poll_votes_id_seq from public, anon, authenticated;

drop policy if exists "Poll options are publicly readable" on public.pano_poll_options;
drop policy if exists "Pano owners can add poll options" on public.pano_poll_options;

drop function if exists public.toggle_pano_poll_vote(bigint);
drop function if exists public.get_pano_poll_voters(uuid);
drop function if exists public.create_pano_poll(text, text, text, bigint, bigint, text, text, boolean, text[]);
drop function if exists public.get_pano_poll(uuid);

create function public.get_pano_poll(p_pano_id uuid)
returns jsonb
language sql
security definer
stable
set search_path = public, auth
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'option_id', option_row.id,
        'label', option_row.label,
        'vote_count', (
          select count(*)
          from public.pano_poll_votes option_votes
          where option_votes.option_id = option_row.id
        ),
        'selected_by_me', exists (
          select 1
          from public.pano_poll_votes my_vote
          where my_vote.option_id = option_row.id
            and my_vote.user_id = auth.uid()
        ),
        'total_voters', (
          select count(distinct all_votes.user_id)
          from public.pano_poll_votes all_votes
          where all_votes.pano_id = p_pano_id
        )
      )
      order by option_row.display_order
    ),
    '[]'::jsonb
  )
  from public.pano_poll_options option_row
  where option_row.pano_id = p_pano_id;
$$;

create function public.toggle_pano_poll_vote(p_option_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  actor_id uuid := auth.uid();
  target_pano_id uuid;
  allows_multiple boolean;
  already_selected boolean;
begin
  if actor_id is null then
    raise exception using message = 'AUTHENTICATION_REQUIRED';
  end if;

  select option_row.pano_id, pano.poll_allows_multiple
  into target_pano_id, allows_multiple
  from public.pano_poll_options option_row
  join public.panolar pano on pano.id = option_row.pano_id
  where option_row.id = p_option_id
    and pano.poll_question is not null;

  if target_pano_id is null then
    raise exception using message = 'PANO_POLL_OPTION_NOT_FOUND';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(actor_id::text || ':' || target_pano_id::text, 0)
  );

  select exists (
    select 1
    from public.pano_poll_votes vote_row
    where vote_row.option_id = p_option_id
      and vote_row.user_id = actor_id
  ) into already_selected;

  if already_selected then
    delete from public.pano_poll_votes
    where option_id = p_option_id
      and user_id = actor_id;
  else
    if not allows_multiple then
      delete from public.pano_poll_votes
      where pano_id = target_pano_id
        and user_id = actor_id;
    end if;

    insert into public.pano_poll_votes (pano_id, option_id, user_id)
    values (target_pano_id, p_option_id, actor_id)
    on conflict (option_id, user_id) do nothing;
  end if;

  return public.get_pano_poll(target_pano_id);
end;
$$;

create function public.get_pano_poll_voters(p_pano_id uuid)
returns jsonb
language plpgsql
security definer
stable
set search_path = public, auth
as $$
declare
  actor_id uuid := auth.uid();
  actor_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  can_view boolean;
  voter_list jsonb;
begin
  select exists (
    select 1
    from public.panolar pano
    where pano.id = p_pano_id
      and (
        pano.user_id = actor_id
        or lower(pano.user_email) = actor_email
        or exists (
          select 1
          from public.announcement_admins admin_row
          where lower(admin_row.user_email) = actor_email
        )
      )
  ) into can_view;

  if actor_id is null or not can_view then
    raise exception using message = 'PANO_POLL_VOTERS_FORBIDDEN';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'option_id', voter.option_id,
        'user_id', voter.user_id,
        'username', voter.username,
        'avatar_url', voter.avatar_url,
        'voted_at', voter.voted_at
      )
      order by voter.voted_at
    ),
    '[]'::jsonb
  )
  into voter_list
  from (
    select
      vote_row.option_id,
      vote_row.user_id,
      coalesce(profile.username, 'Kullanici')::text as username,
      profile.avatar_url::text as avatar_url,
      vote_row.created_at as voted_at
    from public.pano_poll_votes vote_row
    left join public.profiles profile on profile.id = vote_row.user_id
    where vote_row.pano_id = p_pano_id
  ) voter;

  return voter_list;
end;
$$;

create function public.create_pano_poll(
  p_title text,
  p_content text,
  p_username text,
  p_book_id bigint,
  p_chapter_id bigint,
  p_image_url text,
  p_question text,
  p_allows_multiple boolean,
  p_options text[]
)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  created_pano_id uuid;
  cleaned_options text[];
begin
  if auth.uid() is null then
    raise exception using message = 'AUTHENTICATION_REQUIRED';
  end if;

  select array_agg(btrim(option_item.option_label) order by option_item.item_order)
  into cleaned_options
  from unnest(coalesce(p_options, array[]::text[])) with ordinality
    as option_item(option_label, item_order)
  where nullif(btrim(option_item.option_label), '') is not null;

  if char_length(btrim(coalesce(p_question, ''))) not between 3 and 200 then
    raise exception using message = 'PANO_POLL_QUESTION_INVALID';
  end if;

  if coalesce(array_length(cleaned_options, 1), 0) not between 2 and 10 then
    raise exception using message = 'PANO_POLL_OPTIONS_INVALID';
  end if;

  if exists (
    select 1
    from unnest(cleaned_options) as option_item(option_label)
    where char_length(option_item.option_label) > 100
  ) then
    raise exception using message = 'PANO_POLL_OPTION_TOO_LONG';
  end if;

  if (
    select count(*) <> count(distinct lower(option_item.option_label))
    from unnest(cleaned_options) as option_item(option_label)
  ) then
    raise exception using message = 'PANO_POLL_OPTIONS_DUPLICATE';
  end if;

  insert into public.panolar (
    user_email,
    username,
    title,
    content,
    book_id,
    chapter_id,
    image_url,
    poll_question,
    poll_allows_multiple
  ) values (
    auth.jwt() ->> 'email',
    p_username,
    btrim(p_title),
    btrim(p_content),
    p_book_id,
    p_chapter_id,
    nullif(btrim(coalesce(p_image_url, '')), ''),
    btrim(p_question),
    p_allows_multiple
  )
  returning id into created_pano_id;

  insert into public.pano_poll_options (
    pano_id,
    label,
    display_order,
    "position",
    sort_order
  )
  select
    created_pano_id,
    option_item.option_label,
    (option_item.item_order - 1)::integer,
    (option_item.item_order - 1)::integer,
    (option_item.item_order - 1)::integer
  from unnest(cleaned_options) with ordinality
    as option_item(option_label, item_order);

  return created_pano_id;
end;
$$;

revoke all on function public.get_pano_poll(uuid) from public;
revoke all on function public.toggle_pano_poll_vote(bigint) from public;
revoke all on function public.get_pano_poll_voters(uuid) from public;
revoke all on function public.create_pano_poll(text, text, text, bigint, bigint, text, text, boolean, text[]) from public;

grant execute on function public.get_pano_poll(uuid) to anon, authenticated;
grant execute on function public.toggle_pano_poll_vote(bigint) to authenticated;
grant execute on function public.get_pano_poll_voters(uuid) to authenticated;
grant execute on function public.create_pano_poll(text, text, text, bigint, bigint, text, text, boolean, text[]) to authenticated;

create or replace function public.enforce_pano_admin_media_rules()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  actor_id uuid := auth.uid();
  actor_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  actor_is_admin boolean;
  selected_book_is_eligible boolean;
begin
  if actor_id is null or actor_email = '' then
    raise exception 'Authentication is required to create or update panos.';
  end if;

  select exists (
    select 1
    from public.announcement_admins admin_row
    where lower(admin_row.user_email) = actor_email
  ) into actor_is_admin;

  if not actor_is_admin
    and lower(coalesce(new.user_email, '')) <> actor_email
  then
    raise exception 'Users can only create or update their own panos.';
  end if;

  if new.poll_question is not null then
    new.poll_question := btrim(new.poll_question);
  end if;

  if not actor_is_admin then
    if new.book_id is null then
      raise exception using
        message = 'PANO_BOOK_REQUIRED',
        detail = 'Normal kullanicilar anket dahil tum panolar icin kitap secmelidir.';
    end if;

    select exists (
      select 1
      from public.books book
      where book.id = new.book_id
        and book.is_draft = false
        and (
          book.user_id = actor_id
          or (
            book.co_author_id = actor_id
            and book.co_author_status = 'accepted'
          )
        )
        and exists (
          select 1
          from public.chapters chapter
          where chapter.book_id = book.id
            and chapter.is_draft = false
        )
    ) into selected_book_is_eligible;

    if not selected_book_is_eligible then
      raise exception using message = 'PANO_BOOK_REQUIRED';
    end if;
  elsif new.book_id is null
    and new.poll_question is null
    and nullif(btrim(coalesce(new.image_url, '')), '') is null
  then
    raise exception using
      message = 'PANO_IMAGE_REQUIRED',
      detail = 'Kitapsiz admin panolari bir gorsel veya anket icermelidir.';
  end if;

  if new.book_id is null then
    new.chapter_id := null;
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_pano_admin_media_rules on public.panolar;

create trigger enforce_pano_admin_media_rules
before insert or update of
  user_email,
  book_id,
  chapter_id,
  image_url,
  poll_question,
  poll_allows_multiple
on public.panolar
for each row
execute function public.enforce_pano_admin_media_rules();

notify pgrst, 'reload schema';
