-- 500 LabCoin ile 1 aylik Premium uyelik satin alma.
-- Coin dusumu, profil rolu, bitis tarihi ve hareket kaydi tek transaction icinde tutulur.
-- Yalnizca yormeci (Yilmaz Ormeci) hesabi suresiz Premium'dur.

alter table public.profiles
  add column if not exists premium_expires_at timestamptz;

comment on column public.profiles.premium_expires_at is
  'Premium uyeligin bitis zamani. Yalnizca yormeci hesabi icin NULL suresiz uyelik anlamina gelir.';

-- Mevcut Premium hesaplari aylik sisteme tasir. Yilmaz'in hesabi suresiz kalir.
update public.profiles
set
  premium_expires_at = now() + interval '1 month',
  updated_at = now()
where role = 'premium'
  and id <> 'e3cd0953-1674-4a8a-a09d-676a9bcf367b'::uuid
  and premium_expires_at is null;

update public.profiles
set
  role = 'premium',
  premium_expires_at = null,
  updated_at = now()
where id = 'e3cd0953-1674-4a8a-a09d-676a9bcf367b'::uuid;

create table if not exists public.labcoin_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null check (amount <> 0),
  transaction_type text not null,
  reference_key text not null,
  description text,
  created_at timestamptz not null default now(),
  unique (user_id, transaction_type, reference_key)
);

create index if not exists labcoin_transactions_user_time_idx
  on public.labcoin_transactions (user_id, created_at desc);

alter table public.labcoin_transactions enable row level security;

drop policy if exists "Users can view their LabCoin transactions"
on public.labcoin_transactions;
create policy "Users can view their LabCoin transactions"
on public.labcoin_transactions
for select
to authenticated
using (auth.uid() = user_id);

revoke insert, update, delete on public.labcoin_transactions
from anon, authenticated;
grant select on public.labcoin_transactions to authenticated;

-- Normal profil guncellemelerinde rol, Premium bitis tarihi ve ban korumasi devam eder.
-- Yalnizca guvenli satin alma/sona erdirme islemleri korumali alanlari degistirebilir.
create or replace function public.protect_critical_profile_columns()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if exists (
    select 1
    from public.announcement_admins admin
    where lower(admin.user_email) =
      lower(coalesce(auth.jwt() ->> 'email', ''))
  ) then
    return new;
  end if;

  if current_setting('kitaplab.premium_purchase', true) = 'allowed'
    and new.id = auth.uid()
    and new.role = 'premium'
    and new.premium_expires_at > now()
    and new.is_banned is not distinct from old.is_banned
  then
    return new;
  end if;

  if current_setting('kitaplab.premium_expiration', true) = 'allowed'
    and old.role = 'premium'
    and old.premium_expires_at is not null
    and old.premium_expires_at <= now()
    and new.role = 'user'
    and new.premium_expires_at is null
    and new.is_banned is not distinct from old.is_banned
  then
    return new;
  end if;

  if new.role is distinct from old.role then
    new.role := old.role;
  end if;

  if new.premium_expires_at is distinct from old.premium_expires_at then
    new.premium_expires_at := old.premium_expires_at;
  end if;

  if new.is_banned is distinct from old.is_banned then
    new.is_banned := old.is_banned;
  end if;

  return new;
end;
$$;

create or replace function public.can_use_premium_features()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select
    auth.uid() is not null
    and (
      exists (
        select 1
        from public.profiles profile
        where profile.id = auth.uid()
          and profile.role = 'premium'
          and (
            profile.premium_expires_at is null
            or profile.premium_expires_at > now()
          )
      )
      or exists (
        select 1
        from public.announcement_admins admin
        where lower(admin.user_email) =
          lower(coalesce(auth.jwt() ->> 'email', ''))
      )
    );
$$;

create or replace function public.can_use_chapter_images()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select public.can_use_premium_features();
$$;

revoke all on function public.can_use_premium_features() from public, anon;
revoke all on function public.can_use_chapter_images() from public, anon;
grant execute on function public.can_use_premium_features() to authenticated;
grant execute on function public.can_use_chapter_images() to authenticated;

create or replace function public.expire_premium_memberships()
returns integer
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  expired_count integer := 0;
begin
  perform set_config('kitaplab.premium_expiration', 'allowed', true);

  update public.profiles
  set
    role = 'user',
    premium_expires_at = null,
    updated_at = now()
  where role = 'premium'
    and premium_expires_at is not null
    and premium_expires_at <= now();

  get diagnostics expired_count = row_count;
  perform set_config('kitaplab.premium_expiration', 'off', true);

  return expired_count;
end;
$$;

create or replace function public.get_labcoin_status()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  actor_id uuid := auth.uid();
  actor_email text := coalesce(auth.jwt() ->> 'email', '');
  current_balance integer;
  claims_today integer;
  last_claim_at timestamptz;
  next_claim_at timestamptz;
  day_start timestamptz;
  profile_is_premium boolean;
  profile_premium_expires_at timestamptz;
  profile_premium_is_permanent boolean;
  actor_is_admin boolean;
begin
  if actor_id is null then
    raise exception 'Authentication is required.';
  end if;

  perform public.expire_premium_memberships();

  insert into public.labcoin_wallets (user_id)
  values (actor_id)
  on conflict (user_id) do nothing;

  select wallet.balance
  into current_balance
  from public.labcoin_wallets wallet
  where wallet.user_id = actor_id;

  select
    coalesce(
      profile.role = 'premium'
      and (
        profile.premium_expires_at is null
        or profile.premium_expires_at > now()
      ),
      false
    ),
    profile.premium_expires_at,
    coalesce(
      profile.role = 'premium'
      and profile.premium_expires_at is null,
      false
    )
  into
    profile_is_premium,
    profile_premium_expires_at,
    profile_premium_is_permanent
  from public.profiles profile
  where profile.id = actor_id;

  actor_is_admin := exists (
    select 1
    from public.announcement_admins admin
    where lower(admin.user_email) = lower(actor_email)
  );

  day_start :=
    date_trunc('day', timezone('Europe/Istanbul', now()))
    at time zone 'Europe/Istanbul';

  select count(*)::integer, max(claim.claimed_at)
  into claims_today, last_claim_at
  from public.labcoin_reward_claims claim
  where claim.user_id = actor_id
    and claim.claimed_at >= day_start
    and claim.claimed_at < day_start + interval '1 day';

  next_claim_at :=
    case
      when last_claim_at is null then null
      else last_claim_at + interval '30 minutes'
    end;

  return jsonb_build_object(
    'balance', coalesce(current_balance, 0),
    'claims_today', coalesce(claims_today, 0),
    'daily_limit', 4,
    'next_claim_at', next_claim_at,
    'can_claim',
      coalesce(claims_today, 0) < 4
      and (next_claim_at is null or now() >= next_claim_at),
    'is_premium', coalesce(profile_is_premium, false),
    'premium_expires_at', profile_premium_expires_at,
    'premium_is_permanent', coalesce(profile_premium_is_permanent, false),
    'is_admin', actor_is_admin,
    'has_premium_access',
      coalesce(profile_is_premium, false) or actor_is_admin,
    'premium_price', 500,
    'premium_duration_months', 1,
    'can_purchase_premium',
      not (coalesce(profile_is_premium, false) or actor_is_admin)
      and coalesce(current_balance, 0) >= 500,
    'server_now', now()
  );
end;
$$;

create or replace function public.purchase_premium_with_labcoin()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  actor_id uuid := auth.uid();
  actor_email text := coalesce(auth.jwt() ->> 'email', '');
  profile_role text;
  profile_premium_expires_at timestamptz;
  profile_is_active_premium boolean;
  actor_is_admin boolean;
  new_balance integer;
  new_premium_expires_at timestamptz;
  purchase_reference text;
  status_payload jsonb;
begin
  if actor_id is null then
    raise exception 'Authentication is required.';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(actor_id::text, 0));
  perform public.expire_premium_memberships();

  select profile.role, profile.premium_expires_at
  into profile_role, profile_premium_expires_at
  from public.profiles profile
  where profile.id = actor_id
  for update;

  if not found then
    raise exception 'PROFILE_NOT_FOUND';
  end if;

  actor_is_admin := exists (
    select 1
    from public.announcement_admins admin
    where lower(admin.user_email) = lower(actor_email)
  );

  profile_is_active_premium :=
    profile_role = 'premium'
    and (
      profile_premium_expires_at is null
      or profile_premium_expires_at > now()
    );

  if profile_is_active_premium or actor_is_admin then
    status_payload := public.get_labcoin_status();
    return status_payload || jsonb_build_object(
      'purchased', false,
      'already_premium', true
    );
  end if;

  insert into public.labcoin_wallets (user_id)
  values (actor_id)
  on conflict (user_id) do nothing;

  update public.labcoin_wallets wallet
  set
    balance = wallet.balance - 500,
    updated_at = now()
  where wallet.user_id = actor_id
    and wallet.balance >= 500
  returning wallet.balance into new_balance;

  if not found then
    raise exception using
      message = 'LABCOIN_INSUFFICIENT_BALANCE',
      detail = 'Premium uyelik icin 500 LabCoin gerekir.';
  end if;

  new_premium_expires_at := now() + interval '1 month';
  purchase_reference := format(
    'monthly-premium:%s:%s',
    txid_current(),
    clock_timestamp()
  );

  perform set_config('kitaplab.premium_purchase', 'allowed', true);

  update public.profiles
  set
    role = 'premium',
    premium_expires_at = new_premium_expires_at,
    updated_at = now()
  where id = actor_id;

  perform set_config('kitaplab.premium_purchase', 'off', true);

  if not exists (
    select 1
    from public.profiles profile
    where profile.id = actor_id
      and profile.role = 'premium'
      and profile.premium_expires_at = new_premium_expires_at
  ) then
    raise exception 'PREMIUM_ROLE_UPDATE_FAILED';
  end if;

  insert into public.labcoin_transactions (
    user_id,
    amount,
    transaction_type,
    reference_key,
    description
  )
  values (
    actor_id,
    -500,
    'premium_purchase',
    purchase_reference,
    '1 aylik KitapLab Premium uyeligi'
  );

  status_payload := public.get_labcoin_status();
  return status_payload || jsonb_build_object(
    'purchased', true,
    'already_premium', false,
    'balance', new_balance
  );
end;
$$;

create extension if not exists pg_cron;

do $$
declare
  existing_job_id bigint;
begin
  for existing_job_id in
    select jobid
    from cron.job
    where jobname = 'kitaplab-expire-premiums'
  loop
    perform cron.unschedule(existing_job_id);
  end loop;

  perform cron.schedule(
    'kitaplab-expire-premiums',
    '* * * * *',
    'select public.expire_premium_memberships();'
  );
end;
$$;

revoke all on function public.get_labcoin_status() from public, anon;
revoke all on function public.purchase_premium_with_labcoin() from public, anon;
revoke all on function public.expire_premium_memberships() from public, anon, authenticated;
grant execute on function public.get_labcoin_status() to authenticated;
grant execute on function public.purchase_premium_with_labcoin() to authenticated;

notify pgrst, 'reload schema';
