-- LabCoin cuzdanlari ve odullu reklam kazanimlari.
-- Gunluk sinir Europe/Istanbul gunune gore 4, kazanimlar arasi sure 30 dakikadir.

create table if not exists public.labcoin_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance integer not null default 0 check (balance >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.labcoin_reward_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reward_token uuid not null,
  amount integer not null default 1 check (amount = 1),
  claimed_at timestamptz not null default now(),
  unique (user_id, reward_token)
);

create index if not exists labcoin_reward_claims_user_time_idx
  on public.labcoin_reward_claims (user_id, claimed_at desc);

alter table public.labcoin_wallets enable row level security;
alter table public.labcoin_reward_claims enable row level security;

drop policy if exists "Users can view their LabCoin wallet" on public.labcoin_wallets;
create policy "Users can view their LabCoin wallet"
on public.labcoin_wallets
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can view their LabCoin rewards" on public.labcoin_reward_claims;
create policy "Users can view their LabCoin rewards"
on public.labcoin_reward_claims
for select
to authenticated
using (auth.uid() = user_id);

revoke insert, update, delete on public.labcoin_wallets from anon, authenticated;
revoke insert, update, delete on public.labcoin_reward_claims from anon, authenticated;
grant select on public.labcoin_wallets to authenticated;
grant select on public.labcoin_reward_claims to authenticated;

create or replace function public.get_labcoin_status()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  actor_id uuid := auth.uid();
  current_balance integer;
  claims_today integer;
  last_claim_at timestamptz;
  next_claim_at timestamptz;
  day_start timestamptz;
begin
  if actor_id is null then
    raise exception 'Authentication is required.';
  end if;

  insert into public.labcoin_wallets (user_id)
  values (actor_id)
  on conflict (user_id) do nothing;

  select wallet.balance
  into current_balance
  from public.labcoin_wallets wallet
  where wallet.user_id = actor_id;

  day_start :=
    date_trunc('day', timezone('Europe/Istanbul', now()))
    at time zone 'Europe/Istanbul';

  select count(*)::integer, max(claim.claimed_at)
  into claims_today, last_claim_at
  from public.labcoin_reward_claims claim
  where claim.user_id = actor_id
    and claim.claimed_at >= day_start
    and claim.claimed_at < day_start + interval '1 day';

  next_claim_at :=
    case
      when last_claim_at is null then null
      else last_claim_at + interval '30 minutes'
    end;

  return jsonb_build_object(
    'balance', coalesce(current_balance, 0),
    'claims_today', coalesce(claims_today, 0),
    'daily_limit', 4,
    'next_claim_at', next_claim_at,
    'can_claim',
      coalesce(claims_today, 0) < 4
      and (next_claim_at is null or now() >= next_claim_at),
    'server_now', now()
  );
end;
$$;

create or replace function public.claim_labcoin_reward(p_reward_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  actor_id uuid := auth.uid();
  claims_today integer;
  last_claim_at timestamptz;
  next_claim_at timestamptz;
  day_start timestamptz;
  new_balance integer;
  status_payload jsonb;
begin
  if actor_id is null then
    raise exception 'Authentication is required.';
  end if;

  if p_reward_token is null then
    raise exception 'LABCOIN_REWARD_TOKEN_REQUIRED';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(actor_id::text, 0));

  if exists (
    select 1
    from public.labcoin_reward_claims claim
    where claim.user_id = actor_id
      and claim.reward_token = p_reward_token
  ) then
    status_payload := public.get_labcoin_status();
    return status_payload || jsonb_build_object('earned', false, 'duplicate', true);
  end if;

  day_start :=
    date_trunc('day', timezone('Europe/Istanbul', now()))
    at time zone 'Europe/Istanbul';

  select count(*)::integer, max(claim.claimed_at)
  into claims_today, last_claim_at
  from public.labcoin_reward_claims claim
  where claim.user_id = actor_id
    and claim.claimed_at >= day_start
    and claim.claimed_at < day_start + interval '1 day';

  if coalesce(claims_today, 0) >= 4 then
    raise exception using
      message = 'LABCOIN_DAILY_LIMIT_REACHED',
      detail = 'Bir kullanici Istanbul gunune gore en fazla 4 LabCoin kazanabilir.';
  end if;

  next_claim_at :=
    case
      when last_claim_at is null then null
      else last_claim_at + interval '30 minutes'
    end;

  if next_claim_at is not null and now() < next_claim_at then
    raise exception using
      message = 'LABCOIN_COOLDOWN_ACTIVE',
      detail = next_claim_at::text;
  end if;

  insert into public.labcoin_reward_claims (user_id, reward_token, amount)
  values (actor_id, p_reward_token, 1);

  insert into public.labcoin_wallets (user_id, balance)
  values (actor_id, 1)
  on conflict (user_id) do update
    set balance = public.labcoin_wallets.balance + 1,
        updated_at = now()
  returning balance into new_balance;

  status_payload := public.get_labcoin_status();
  return status_payload || jsonb_build_object(
    'earned', true,
    'duplicate', false,
    'balance', new_balance
  );
end;
$$;

revoke all on function public.get_labcoin_status() from public, anon;
revoke all on function public.claim_labcoin_reward(uuid) from public, anon;
grant execute on function public.get_labcoin_status() to authenticated;
grant execute on function public.claim_labcoin_reward(uuid) to authenticated;

notify pgrst, 'reload schema';
